-- 코드를 입력하세요
-- 이상해.. 왜케 복잡한 느낌이 들지? 아무튼 정답!
SELECT TBL.MEMBER_NAME
, R2.REVIEW_TEXT
, DATE_FORMAT(R2.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R2 JOIN (
    SELECT P.MEMBER_ID, P.MEMBER_NAME
    FROM MEMBER_PROFILE P LEFT JOIN REST_REVIEW R1
    ON P.MEMBER_ID = R1.MEMBER_ID 
    GROUP BY P.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) MAX_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY MAX_COUNT DESC LIMIT 1
        )
    ) TBL
ON R2.MEMBER_ID = TBL.MEMBER_ID
ORDER BY R2.REVIEW_DATE, R2.REVIEW_TEXT;