-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F LEFT OUTER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ) TBL
    ON F.FLAVOR = TBL.FLAVOR
ORDER BY (F.TOTAL_ORDER+TBL.TOTAL_ORDER) DESC LIMIT 3;