SELECT MONTH(C1.START_DATE) MONTH, C1.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1 JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) C2 ON C1.CAR_ID = C2.CAR_ID
WHERE DATE_FORMAT(C1.START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(C1.START_DATE, '%Y-%m') <= '2022-10'
GROUP BY MONTH(C1.START_DATE), C1.CAR_ID
ORDER BY MONTH(C1.START_DATE), C1.CAR_ID DESC;