SELECT D.DEPT_ID, D.DEPT_NAME_EN, E.AVG_SAL
FROM HR_DEPARTMENT D, (
    SELECT DEPT_ID, ROUND(AVG(SAL),0) AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) E
WHERE D.DEPT_ID = E.DEPT_ID
ORDER BY E.AVG_SAL DESC;