SELECT F.CATEGORY, F.PRICE MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE 
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자','국','김치','식용유')
    ORDER BY MAX(PRICE) DESC
) TBL
WHERE F.PRICE = TBL.MAX_PRICE AND F.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY F.PRICE DESC;