SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT O.USER_ID) USERS
FROM ONLINE_SALE O LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER;