# 이번 문제를 통해 HOUR 만드는 법 배움!
WITH RECURSIVE NUM AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM NUM
    WHERE HOUR < 23
    )

SELECT N.HOUR, IFNULL(T.CNT, 0) COUNT
FROM NUM N LEFT OUTER JOIN (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) T ON N.HOUR = T.HOUR;