SELECT N_TBL.AUTHOR_ID, N_TBL.AUTHOR_NAME, N_TBL.CATEGORY, SUM(N_TBL.TOTAL_SALES) TOTAL_SALES
FROM (
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.AUTHOR_NAME, B.PRICE, TBL.TOT_SALES, (B.PRICE*TBL.TOT_SALES) TOTAL_SALES
    FROM BOOK B, AUTHOR A, (
        SELECT BOOK_ID, SUM(SALES) TOT_SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
        GROUP BY BOOK_ID
    ) TBL
    WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = TBL.BOOK_ID
) N_TBL
GROUP BY N_TBL.AUTHOR_ID, N_TBL.CATEGORY
ORDER BY N_TBL.AUTHOR_ID, N_TBL.CATEGORY DESC;
