SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES
FROM USED_GOODS_USER U, (
    SELECT WRITER_ID USER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
    ) T
WHERE U.USER_ID = T.USER_ID
ORDER BY T.TOTAL_SALES;