SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R, (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) TBL
WHERE R.FOOD_TYPE = TBL.FOOD_TYPE AND R.FAVORITES = TBL.FAVORITES
ORDER BY R.FOOD_TYPE DESC;