SELECT B.CATEGORY, SUM(S.TOTAL_SALES) TOTAL_SALES
FROM BOOK B, (
    SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
    ) S
WHERE B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;