SELECT COUNT(TBL.N_LENGTH) FISH_COUNT, MAX(TBL.N_LENGTH) MAX_LENGTH, FISH_TYPE
FROM (
    SELECT *, IFNULL(LENGTH, 10) N_LENGTH
    FROM FISH_INFO
) TBL
GROUP BY TBL.FISH_TYPE
HAVING AVG(TBL.N_LENGTH) >= 33
ORDER BY TBL.FISH_TYPE;  # 정렬하지 않아서 계속 실패 받은.. 하..